<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Curtain" Id="{2c931182-f172-4d5b-8036-a8af64d500b0}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Curtain
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>