<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Room" Id="{442c75c1-7593-4393-b6bc-5705fce27c62}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Room
VAR_INPUT
	keypad1 : FB_Keypad_4x2_Tap;
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>