<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="PRG_SmartHome" Id="{3a9a704e-ac95-4023-9fa2-f778a7ebe871}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_SmartHome
VAR
	fbRoom: ARRAY[0..1] OF FB_Room;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
	fbRoom[0]();
	fbRoom[1]();
	PRG_HallRoom();
	PRG_Kitchen();
	
	







]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>