<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Keypad_4x2_Tap" Id="{62204366-1607-4ea6-aa09-a6fea29f7c55}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Keypad_4x2_Tap
VAR_INPUT
	Key: ARRAY [0..7] OF ST_DigitalInput;
END_VAR
VAR_OUTPUT
	KeyEvent: ARRAY[0..7] OF BOOL;
END_VAR
VAR
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[


















]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>