<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_RotarySwitch" Id="{6d710a60-bff5-430c-984d-ea47640f8202}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_RotarySwitch
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>