<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_TapButton" Id="{0b04fee2-8e62-40ea-8cee-6a7f03323788}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_TapButton
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>