<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_ToggleButton" Id="{20c11092-cf81-40f5-b982-887e95a4637e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_ToggleButton
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>